name: serviceRegistry
description: A registry of services running on other isolates.
version: 0.0.1
author: Ray King <email@example.com>
homepage: https://github.com/rayk/serviceRegistry

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  stream_channel: "^1.3.1"
  string_scanner: "^0.1.4+1"
  source_span: "^1.2.2"
  resource: "^1.1.0"


dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  path: any
